stagate:
  name: intSTAGATE
  params:
      in_features: 3000
      architecture: MLP
      hidden_dims: [512, 30]
      gradient_clipping: 5.0

  optimizer:
    name: ADAM
    params:
      lr: 0.0001
      weight_decay: 0.0001
  scheduler:
    name: STEP_LR
    params:
      step_size: 1000
      gamma: 0.9

clustering:
  r_seed: 2020
  n_clusters: 7
  model_name: EEE

mlp:
  balanced: True
  test_prop: 0.1
  target_class: 3
  optimizer:
    name: ADAM
    params:
      lr: 0.001
      weight_decay: 0.0001
  scheduler:
    name: STEP_LR
    params:
      step_size: 250
      gamma: 0.5